/*
 * swagger example API
 *
 * API to demo swagger
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 *
 * Hooray! It's out custom header
 *
 */
package models

type PropertyInfoData struct {
	// Field that indicates the status of a property on the channel. Accepted values are \"active\" for a property that is opened and bookable, \"inactive\" for a property that is no longer open and bookable, \"inactive_checks\" when a property is currently closed but will be opened after optional checks are done, \"inactive_temporary\" when a property was opened but it is now closed for a short period of time while resolving an issue, \"inactive_duplicate\" when a property already exists on the channel with a different property id or provider.
	PropertyStatus *string `json:"propertyStatus,omitempty"`
	// This field can be used to provide more information as to why a property has a specific status on the channel.
	PropertyStatusNote *string `json:"propertyStatusNote,omitempty"`
	// This field can be used to provide the property direct url on the channel.
	PropertyUrl *string `json:"propertyUrl,omitempty"`
	// This field can be used to provide a property score or rating on the channel. It is used together with the propertyRatingScale to indicate the score and scale. Example 4 out of 5 where 4 is the rating and 5 is the scale. This value cannot be bigger than the propertyRatingScale.
	PropertyRating *float64 `json:"propertyRating,omitempty"`
	// This field can be used to indicate the scale used for the property rating. It is required if channelPropertyRating field has a value.
	RatingScale *int32 `json:"ratingScale,omitempty"`
}
