/*
 * swagger example API
 *
 * API to demo swagger
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 *
 * Hooray! It's out custom header
 *
 */
package models

type GenericErrorResponse struct {
	Code string `json:"Code"`

	ErrorCode string `json:"ErrorCode"`

	Message string `json:"Message"`

	RequestId string `json:"RequestId"`
}
