/*
 * swagger example API
 *
 * API to demo swagger
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 *
 * Hooray! It's out custom header
 *
 */
package models

type PropertyInfoResponse struct {
	Data *PropertyInfoData `json:"data,omitempty"`

	RequestId string `json:"requestId"`
}
