// Code generated by go-swagger; DO NOT EDIT.

// Package sw2 stats
//
//	Some description of your amazing service
//	Schemes:
//	  http
//	Host: stats.api.ru
//	BasePath: /accounts
//	Version: 1.9.9
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package sw2
