// Package oapi_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi_server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "github.com/grbit/swagger-example/pkg/codegen/models"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves properties information
	// (GET /property)
	GetPropertiesInfo(w http.ResponseWriter, r *http.Request)
	// Retrieves property information by ID
	// (GET /property/{propertyId})
	GetPropertyInfoById(w http.ResponseWriter, r *http.Request, propertyId string)
	// Set/Update property information by ID
	// (POST /property/{propertyId})
	CreateUpdatePropertyInfoById(w http.ResponseWriter, r *http.Request, propertyId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetPropertiesInfo operation middleware
func (siw *ServerInterfaceWrapper) GetPropertiesInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, OpenIdProdScopes, []string{""})

	ctx = context.WithValue(ctx, OpenIdSandboxScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPropertiesInfo(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPropertyInfoById operation middleware
func (siw *ServerInterfaceWrapper) GetPropertyInfoById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "propertyId", runtime.ParamLocationPath, chi.URLParam(r, "propertyId"), &propertyId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, OpenIdProdScopes, []string{""})

	ctx = context.WithValue(ctx, OpenIdSandboxScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPropertyInfoById(w, r, propertyId)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateUpdatePropertyInfoById operation middleware
func (siw *ServerInterfaceWrapper) CreateUpdatePropertyInfoById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "propertyId", runtime.ParamLocationPath, chi.URLParam(r, "propertyId"), &propertyId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, OpenIdProdScopes, []string{""})

	ctx = context.WithValue(ctx, OpenIdSandboxScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUpdatePropertyInfoById(w, r, propertyId)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/property", wrapper.GetPropertiesInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/property/{propertyId}", wrapper.GetPropertyInfoById)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/property/{propertyId}", wrapper.CreateUpdatePropertyInfoById)
	})

	return r
}

type GetPropertiesInfoRequestObject struct {
}

type GetPropertiesInfoResponseObject interface {
	VisitGetPropertiesInfoResponse(w http.ResponseWriter) error
}

type GetPropertiesInfo200JSONResponse PropertiesInfoResponse

func (response GetPropertiesInfo200JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfo400JSONResponse GenericErrorResponse

func (response GetPropertiesInfo400JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfo404Response struct {
}

func (response GetPropertiesInfo404Response) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPropertiesInfo500JSONResponse GenericErrorResponse

func (response GetPropertiesInfo500JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfo501JSONResponse GenericErrorResponse

func (response GetPropertiesInfo501JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfodefaultResponse struct {
	StatusCode int
}

func (response GetPropertiesInfodefaultResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type GetPropertyInfoByIdRequestObject struct {
	PropertyId string `json:"propertyId"`
}

type GetPropertyInfoByIdResponseObject interface {
	VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error
}

type GetPropertyInfoById200JSONResponse PropertyInfoResponse

func (response GetPropertyInfoById200JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoById400JSONResponse GenericErrorResponse

func (response GetPropertyInfoById400JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoById404Response struct {
}

func (response GetPropertyInfoById404Response) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPropertyInfoById500JSONResponse GenericErrorResponse

func (response GetPropertyInfoById500JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoById501JSONResponse GenericErrorResponse

func (response GetPropertyInfoById501JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoByIddefaultResponse struct {
	StatusCode int
}

func (response GetPropertyInfoByIddefaultResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type CreateUpdatePropertyInfoByIdRequestObject struct {
	PropertyId string `json:"propertyId"`
	Body       *CreateUpdatePropertyInfoByIdJSONRequestBody
}

type CreateUpdatePropertyInfoByIdResponseObject interface {
	VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error
}

type CreateUpdatePropertyInfoById200JSONResponse PropertyInfoResponse

func (response CreateUpdatePropertyInfoById200JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoById400JSONResponse GenericErrorResponse

func (response CreateUpdatePropertyInfoById400JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoById404Response struct {
}

func (response CreateUpdatePropertyInfoById404Response) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateUpdatePropertyInfoById500JSONResponse GenericErrorResponse

func (response CreateUpdatePropertyInfoById500JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoById501JSONResponse GenericErrorResponse

func (response CreateUpdatePropertyInfoById501JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoByIddefaultResponse struct {
	StatusCode int
}

func (response CreateUpdatePropertyInfoByIddefaultResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieves properties information
	// (GET /property)
	GetPropertiesInfo(ctx context.Context, request GetPropertiesInfoRequestObject) (GetPropertiesInfoResponseObject, error)
	// Retrieves property information by ID
	// (GET /property/{propertyId})
	GetPropertyInfoById(ctx context.Context, request GetPropertyInfoByIdRequestObject) (GetPropertyInfoByIdResponseObject, error)
	// Set/Update property information by ID
	// (POST /property/{propertyId})
	CreateUpdatePropertyInfoById(ctx context.Context, request CreateUpdatePropertyInfoByIdRequestObject) (CreateUpdatePropertyInfoByIdResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetPropertiesInfo operation middleware
func (sh *strictHandler) GetPropertiesInfo(w http.ResponseWriter, r *http.Request) {
	var request GetPropertiesInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPropertiesInfo(ctx, request.(GetPropertiesInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPropertiesInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPropertiesInfoResponseObject); ok {
		if err := validResponse.VisitGetPropertiesInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetPropertyInfoById operation middleware
func (sh *strictHandler) GetPropertyInfoById(w http.ResponseWriter, r *http.Request, propertyId string) {
	var request GetPropertyInfoByIdRequestObject

	request.PropertyId = propertyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPropertyInfoById(ctx, request.(GetPropertyInfoByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPropertyInfoById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPropertyInfoByIdResponseObject); ok {
		if err := validResponse.VisitGetPropertyInfoByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// CreateUpdatePropertyInfoById operation middleware
func (sh *strictHandler) CreateUpdatePropertyInfoById(w http.ResponseWriter, r *http.Request, propertyId string) {
	var request CreateUpdatePropertyInfoByIdRequestObject

	request.PropertyId = propertyId

	var body CreateUpdatePropertyInfoByIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUpdatePropertyInfoById(ctx, request.(CreateUpdatePropertyInfoByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUpdatePropertyInfoById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUpdatePropertyInfoByIdResponseObject); ok {
		if err := validResponse.VisitCreateUpdatePropertyInfoByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY3W/bOBL/V7i8e7Qtf8SN67c07S0M7CWB3QALpMGBJkcWtxKpJUd2dYX/98NQki1/",
	"9GN7yfYlT3Fozm9mfvNJf+bSZrk1YNDz6WfuZQKZCB9/BQNOy3fOWTcHn1vjgc5zZ3NwqCHcurYqnMIn",
	"keUp8CmXMBGwHIy66nIy6l7Eo8vuZDQedIeTyfjV5ethHA8V73Asc7rt0Wmz4tsOD4pO4W7e/f6++24+",
	"v513X08G5wT/Dd6L1ZHYwmbAtIktE0tbIMMEGJCGcwhz+LMAjzN1iKFeyclF3B8Ol/L1xVL0J+PxRMSX",
	"k8uRHMVjccaYbYc7+LPQDhSfPlTk7A1s+9hW+rjDscs/QCKZdLdjeWZi+2X+lUBBfzVCFg7+6SDmU/6P",
	"aB/YqI5qVIOWBPmWBLc7zcI5UfLa/ufgYo/7uHdvb8mJY/V/5VwgwZGr4KXTOWpr+JS/T7RnsYZUMSkM",
	"WwIrPCiGluXOrrUCJliDwby0Dph1zAU0Zk1ICJkIYyDtsRky7RuAFWACjm00JuHWoSULKVIgNdooLQVC",
	"uFMpEEYxT9/32LuKOXbBKPtszMZsk4CjA+2DSG0KyYybs1o4+LYWaQHkm7FI7i31agWOYSLMl8zq8c4+",
	"ZONdREyRLcFRcBuZBQos/Cmp/wp8YiJw515tWBAgP1qsHrN4JSXkCKoy3TPhgH3gQqJewwfOYuva0pUW",
	"z2wOBlTgYWntR7FMocM+cG2+JWgsS60hTgjiiwD/kQnIj/4DpwCYNpD2TBbOgcG0ZDK1FP5lgWyj05QY",
	"byyLMeggjkTKKrjgnLLmUBVCllsnXHlG20bsfCUluvZh02iuvPSJdchycNoqoht1BmyT6BSYA2/TdZUz",
	"THtfHOpWRZ6GiJ3RLVIHQpUMPmmP/ihwVaYLpnQcA7HRYkhR0dQF5UJ6mSKjcq6U8s5Of+tjt6KofbIj",
	"pn24s5g64L7V7PBO+vRh+t5YhB/pCxmVKo0GlwkSYsLT15ukbFOWCE/hyEHqWMtdARymfLveKs3t5Mq0",
	"9xSuRK+SrgPP8sSi9b2vuXbv0h/xqd0QmNIOJLLCpV+1N0HM/TSKNptNr7kgbRaJTPxXm1W3wesOhqNz",
	"Jrt94/krJh/1TeqmRZP/B25U+E1zbmYJ03Hjzt1BB6y1VXELHejA3UF/54I2CCtqiNsvD97y+8buX522",
	"f8d03Xa4B1k4jeWCTKksptYzU3fOqtNg0SkTBSa8w+PUboKATDUYvHagwKAWaTh0EDvwSchSHpFI5ECk",
	"mY9ErqPcWbTSphEp06orrTEgMUL7EQzvcC9tHqwh4unsh3DaYSPJIRFbubcQRi3tp1MP6y/+Xyd9BdN9",
	"Kme/H++M03REbezU26u7GVWagswyvxG0N1AGaQzJVp+wOv3Y1d2Md/ganK+kB71+r99wKnLNp3zU6/co",
	"CXOBSaAoaqqU/lkB1hnmQkOl7Oa/Ah7usJwytqqnADHs90MErEEwAUDk1TzQ1kR/eLKleZB8Z6kdb8uB",
	"okNqfCEleGonzZ0Ov3hCS86+ms7Y8UYoVr8AfqlsuDiN4xy8LZykRQNoV8BqgNP98U+w+d58NHZjmAe3",
	"DvlD65625pfKoMHfbtCNRaYphzMwCCrYoSAWRYqnZN4b+JSDpP00AIeS8kWW0VZCXKPTsIbdCNfg21tC",
	"uL5L++hz82mmtt9RA2EIvClnKhSRExkgOM+nD6dzE5i0Co5WbbTM1QZWOUADr9nf2rtM7Gx2MPaGo4vx",
	"KzrI0/C2jkXqgRoHn4Zy5h1uREZ9Ye8Rbw8XdAV0WoE72QM8llVfCaHg28fnL/Typcxfyvxpyrw8KJ9l",
	"yWZvwz5u/ZmCvnYgEO5zJRCerrI9ID2zigB7vqrD71Y/vahDHr+xqnyWeq525NPw1/XDFtW6Qu/8RQV+",
	"7NH2pfM8SefpvbSeZ2g9C8Coah1f7T3t91toI+2X28PjtvP5+LHz8EjlWXF2rvM83M1v395fv5/d3tTM",
	"PvIOL8JzpPkRgDgSpuyJPA9PsPWAk6YjoMXVzds3t79/E8VrhG9A/XZ7ffXbWaBpFKVWijSxHqeT/qS/",
	"Q3nc/i8AAP//UsFkDrAYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
