// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AdPosts ad posts
//
// swagger:model ad_posts
type AdPosts struct {

	// ad id
	// Required: true
	AdID *ID `json:"ad_id"`

	// day
	// Required: true
	Day *DayDate `json:"day"`

	// ad posts additional properties
	AdPostsAdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *AdPosts) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// ad id
		// Required: true
		AdID *ID `json:"ad_id"`

		// day
		// Required: true
		Day *DayDate `json:"day"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv AdPosts

	rcv.AdID = stage1.AdID
	rcv.Day = stage1.Day
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "ad_id")
	delete(stage2, "day")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.AdPostsAdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m AdPosts) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// ad id
		// Required: true
		AdID *ID `json:"ad_id"`

		// day
		// Required: true
		Day *DayDate `json:"day"`
	}

	stage1.AdID = m.AdID
	stage1.Day = m.Day

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.AdPostsAdditionalProperties) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.AdPostsAdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this ad posts
func (m *AdPosts) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDay(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdPosts) validateAdID(formats strfmt.Registry) error {

	if err := validate.Required("ad_id", "body", m.AdID); err != nil {
		return err
	}

	if err := validate.Required("ad_id", "body", m.AdID); err != nil {
		return err
	}

	if m.AdID != nil {
		if err := m.AdID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ad_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ad_id")
			}
			return err
		}
	}

	return nil
}

func (m *AdPosts) validateDay(formats strfmt.Registry) error {

	if err := validate.Required("day", "body", m.Day); err != nil {
		return err
	}

	if err := validate.Required("day", "body", m.Day); err != nil {
		return err
	}

	if m.Day != nil {
		if err := m.Day.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("day")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("day")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this ad posts based on the context it is used
func (m *AdPosts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdPosts) contextValidateAdID(ctx context.Context, formats strfmt.Registry) error {

	if m.AdID != nil {
		if err := m.AdID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ad_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ad_id")
			}
			return err
		}
	}

	return nil
}

func (m *AdPosts) contextValidateDay(ctx context.Context, formats strfmt.Registry) error {

	if m.Day != nil {
		if err := m.Day.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("day")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("day")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AdPosts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdPosts) UnmarshalBinary(b []byte) error {
	var res AdPosts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
