// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Day Statistics day timestamp in unix time
//
// swagger:model day
type Day int64

// Validate validates this day
func (m Day) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this day based on context it is used
func (m Day) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
