// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DayDate Statistics day date in YYYY-MM-DD format
//
// swagger:model day_date
type DayDate string

// Validate validates this day date
func (m DayDate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this day date based on context it is used
func (m DayDate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
