// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Next link to next page of results by main request
//
// swagger:model next
type Next string

// Validate validates this next
func (m Next) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this next based on context it is used
func (m Next) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
