// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Ok ok
//
// swagger:model ok
type Ok struct {

	// result
	Result *string `json:"result,omitempty"`
}

// Validate validates this ok
func (m *Ok) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ok based on context it is used
func (m *Ok) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Ok) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ok) UnmarshalBinary(b []byte) error {
	var res Ok
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
