// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Total Total records finded by request
//
// swagger:model total
type Total int64

// Validate validates this total
func (m Total) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this total based on context it is used
func (m Total) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
