// Package oapi_echo_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi_echo_server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "github.com/grbit/swagger-example/pkg/codegen/models"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves properties information
	// (GET /property)
	GetPropertiesInfo(ctx echo.Context) error
	// Retrieves property information by ID
	// (GET /property/{propertyId})
	GetPropertyInfoById(ctx echo.Context, propertyId string) error
	// Set/Update property information by ID
	// (POST /property/{propertyId})
	CreateUpdatePropertyInfoById(ctx echo.Context, propertyId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPropertiesInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetPropertiesInfo(ctx echo.Context) error {
	var err error

	ctx.Set(OpenIdProdScopes, []string{""})

	ctx.Set(OpenIdSandboxScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPropertiesInfo(ctx)
	return err
}

// GetPropertyInfoById converts echo context to params.
func (w *ServerInterfaceWrapper) GetPropertyInfoById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "propertyId" -------------
	var propertyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "propertyId", runtime.ParamLocationPath, ctx.Param("propertyId"), &propertyId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter propertyId: %s", err))
	}

	ctx.Set(OpenIdProdScopes, []string{""})

	ctx.Set(OpenIdSandboxScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPropertyInfoById(ctx, propertyId)
	return err
}

// CreateUpdatePropertyInfoById converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUpdatePropertyInfoById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "propertyId" -------------
	var propertyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "propertyId", runtime.ParamLocationPath, ctx.Param("propertyId"), &propertyId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter propertyId: %s", err))
	}

	ctx.Set(OpenIdProdScopes, []string{""})

	ctx.Set(OpenIdSandboxScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUpdatePropertyInfoById(ctx, propertyId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/property", wrapper.GetPropertiesInfo)
	router.GET(baseURL+"/property/:propertyId", wrapper.GetPropertyInfoById)
	router.POST(baseURL+"/property/:propertyId", wrapper.CreateUpdatePropertyInfoById)

}

type GetPropertiesInfoRequestObject struct {
}

type GetPropertiesInfoResponseObject interface {
	VisitGetPropertiesInfoResponse(w http.ResponseWriter) error
}

type GetPropertiesInfo200JSONResponse PropertiesInfoResponse

func (response GetPropertiesInfo200JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfo400JSONResponse GenericErrorResponse

func (response GetPropertiesInfo400JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfo404Response struct {
}

func (response GetPropertiesInfo404Response) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPropertiesInfo500JSONResponse GenericErrorResponse

func (response GetPropertiesInfo500JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfo501JSONResponse GenericErrorResponse

func (response GetPropertiesInfo501JSONResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertiesInfodefaultResponse struct {
	StatusCode int
}

func (response GetPropertiesInfodefaultResponse) VisitGetPropertiesInfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type GetPropertyInfoByIdRequestObject struct {
	PropertyId string `json:"propertyId"`
}

type GetPropertyInfoByIdResponseObject interface {
	VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error
}

type GetPropertyInfoById200JSONResponse PropertyInfoResponse

func (response GetPropertyInfoById200JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoById400JSONResponse GenericErrorResponse

func (response GetPropertyInfoById400JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoById404Response struct {
}

func (response GetPropertyInfoById404Response) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPropertyInfoById500JSONResponse GenericErrorResponse

func (response GetPropertyInfoById500JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoById501JSONResponse GenericErrorResponse

func (response GetPropertyInfoById501JSONResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetPropertyInfoByIddefaultResponse struct {
	StatusCode int
}

func (response GetPropertyInfoByIddefaultResponse) VisitGetPropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type CreateUpdatePropertyInfoByIdRequestObject struct {
	PropertyId string `json:"propertyId"`
	Body       *CreateUpdatePropertyInfoByIdJSONRequestBody
}

type CreateUpdatePropertyInfoByIdResponseObject interface {
	VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error
}

type CreateUpdatePropertyInfoById200JSONResponse PropertyInfoResponse

func (response CreateUpdatePropertyInfoById200JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoById400JSONResponse GenericErrorResponse

func (response CreateUpdatePropertyInfoById400JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoById404Response struct {
}

func (response CreateUpdatePropertyInfoById404Response) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateUpdatePropertyInfoById500JSONResponse GenericErrorResponse

func (response CreateUpdatePropertyInfoById500JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoById501JSONResponse GenericErrorResponse

func (response CreateUpdatePropertyInfoById501JSONResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type CreateUpdatePropertyInfoByIddefaultResponse struct {
	StatusCode int
}

func (response CreateUpdatePropertyInfoByIddefaultResponse) VisitCreateUpdatePropertyInfoByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieves properties information
	// (GET /property)
	GetPropertiesInfo(ctx context.Context, request GetPropertiesInfoRequestObject) (GetPropertiesInfoResponseObject, error)
	// Retrieves property information by ID
	// (GET /property/{propertyId})
	GetPropertyInfoById(ctx context.Context, request GetPropertyInfoByIdRequestObject) (GetPropertyInfoByIdResponseObject, error)
	// Set/Update property information by ID
	// (POST /property/{propertyId})
	CreateUpdatePropertyInfoById(ctx context.Context, request CreateUpdatePropertyInfoByIdRequestObject) (CreateUpdatePropertyInfoByIdResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetPropertiesInfo operation middleware
func (sh *strictHandler) GetPropertiesInfo(ctx echo.Context) error {
	var request GetPropertiesInfoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPropertiesInfo(ctx.Request().Context(), request.(GetPropertiesInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPropertiesInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPropertiesInfoResponseObject); ok {
		return validResponse.VisitGetPropertiesInfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetPropertyInfoById operation middleware
func (sh *strictHandler) GetPropertyInfoById(ctx echo.Context, propertyId string) error {
	var request GetPropertyInfoByIdRequestObject

	request.PropertyId = propertyId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPropertyInfoById(ctx.Request().Context(), request.(GetPropertyInfoByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPropertyInfoById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPropertyInfoByIdResponseObject); ok {
		return validResponse.VisitGetPropertyInfoByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// CreateUpdatePropertyInfoById operation middleware
func (sh *strictHandler) CreateUpdatePropertyInfoById(ctx echo.Context, propertyId string) error {
	var request CreateUpdatePropertyInfoByIdRequestObject

	request.PropertyId = propertyId

	var body CreateUpdatePropertyInfoByIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUpdatePropertyInfoById(ctx.Request().Context(), request.(CreateUpdatePropertyInfoByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUpdatePropertyInfoById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUpdatePropertyInfoByIdResponseObject); ok {
		return validResponse.VisitCreateUpdatePropertyInfoByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY3W/bOBL/V7i8e5Qtx44b129p2lsY6CWB3QALpMGBJkcWtxKpJUd2dYX/98NQki1/",
	"9GN76e5Ln+LQnN/M/OaT/sSlzQtrwKDn00/cyxRyET7+Cgaclm+cs24OvrDGA50XzhbgUEO4dWNVOIWP",
	"Ii8y4FMuYSJgeTHqqavJqHeZjK56k9H4ojecTMYvrl4Ok2SoeMSxKui2R6fNim8jHhSdwt2++e1d7818",
	"fjfvvZxcnBP8N3gvVkdiC5sD0yaxTCxtiQxTYEAaziHM4Y8SPM7UIYZ6ISeXyWA4XMqXl0sxmIzHE5Fc",
	"Ta5GcpSMxRljthF38EepHSg+fazJ2RvY9bGr9GmHY5e/g0Qy6X7H8swk9vP8K4GC/mqEPBz800HCp/wf",
	"8T6wcRPVuAGtCPI1CW53moVzouKN/T+Ciz3u0969vSUnjjX/VXOBBEeugpdOF6it4VP+LtWeJRoyxaQw",
	"bAms9KAYWlY4u9YKmGAtBvPSOmDWMRfQmDUhIWQqjIGsz2bItG8BVoApOLbRmIZbh5YspMiA1GijtBQI",
	"4U6tQBjFPH3fZ29q5tglo+yzCRuzTQqODrQPIo0pJDNuzxrh4NtaZCWQb8YiubfUqxU4hqkwnzOrz6N9",
	"yMa7iJgyX4Kj4LYyCxRY+lNS/xX4xFTgzr3GsCBAfnRYPWbxWkooEFRtumfCAXvPhUS9hvecJdZ1pWst",
	"ntkCDKjAw9LaD2KZQcTec22+Jmgsy6whTgjiswD/kSnID/49pwCYLpD2TJbOgcGsYjKzFP5liWyjs4wY",
	"by1LMOggjkTGarjgnLLmUBVCXlgnXHVG20bsfCUluvFh02quvfSpdcgKcNoqoht1DmyT6gyYA2+zdZ0z",
	"THtfHupWZZGFiJ3RLTIHQlUMPmqP/ihwdaYLpnSSALHRYUhR0TQF5UJ6mTKncq6V8minv/OxV1PUPdkR",
	"0z3cWUwdcN9qdngnffowfW8twvf0hZxKlUaDywUJMeHp601adSlLhadwFCB1ouWuAA5TvltvteZucuXa",
	"ewpXqldpz4FnRWrR+v6XXHtw2ff41G0ITGkHElnpsi/amyIWfhrHm82m316QNo9FLv6rzarX4vUuhjzi",
	"uTZvwaww5dOLwRkH3L4N/RkHjroo9dayrYYDp2r8tlW3k4XppHXu/qAfNtrqKIZ+dOB8xwVtEFbUHo8G",
	"VjciX5jQ1bfN5z87lv+KMbyNuAdZOo3VgkypLaYeNVP3zqrTONIpEyWmPOJJZjdBQGYaDN44UGBQiywc",
	"Okgc+DSkM49JJHYgstzHotBx4SxaabOYlGnVk9YYkBij/QCGR9xLWwRraEGhs+/C2e7XG0uSQyK2dm8h",
	"jFraj6ceNl/8v076Gqb3XM5+O94Zp+mI+t2pt9f3MypCBbllfiNowaAM0hiSrTlhTfqx6/sZj/ganK+l",
	"L/qD/qDlVBSaT/moP+hTEhYC00BR3JYR/bMCbDLMhc5L2c1/BTxcdjllbF1PAWI4GIQIWINgAoAo6sGh",
	"rYl/92RL+3L5xlI7XqsDRYfU+FJK8NRp2jsRv3xGS84+r87Y8Uoo1jwVfqltuDyN4xy8LZ2kjQRoqcB6",
	"0tP98d9g84P5YOzGMA9uHfKH9kJtzS+1QRd/uUG3FpmmHM7BIKhgh4JElBmekvlg4GMBkhbZABxKypd5",
	"TusLcY1Owxp2s16D764T4fou7eNP7aeZ2n5DDYQh8KqaqVBETuSA4DyfPp6OVGDSKjjaydEy1xhY5wDN",
	"wnbR6y49ibP5wUQcji7HL+igyMIjPBGZB2ocfBrKmUfciJz6wt4j3h0u6EqIOoE7WRE8VnVfCaHg26cf",
	"X+jVzzL/WebPU+bVQfksKzZ7HRZ3688U9I0DgfBQKIHwfJXtAek9VgbY81UdfuD624s65PErq6ofUs/1",
	"jnwa/qZ+2KJeV4RRbFGDH3u0/dl5nqXz9H+2nh/QehaAcd06vth7uu+30Ea6L7fHp2306fix8/hE5Vlz",
	"dq7zPN7P714/3Lyb3d02zD7xiJfhOdL+WkAcCVP1RVGEJ9j6gpOmI6DF9e3rV3e/fRXFa4SvQL29u7l+",
	"exZoGseZlSJLrcfpZDAZ7FCetv8LAAD//zuDPY7ZGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
