// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package models

const (
	OpenIdProdScopes    = "openIdProd.Scopes"
	OpenIdSandboxScopes = "openIdSandbox.Scopes"
)

// Defines values for PropertyInfoDataPropertyStatus.
const (
	Active            PropertyInfoDataPropertyStatus = "active"
	Inactive          PropertyInfoDataPropertyStatus = "inactive"
	InactiveChecks    PropertyInfoDataPropertyStatus = "inactive-checks"
	InactiveDuplicate PropertyInfoDataPropertyStatus = "inactive-duplicate"
	InactiveTemporary PropertyInfoDataPropertyStatus = "inactive-temporary"
)

// GenericErrorResponse defines model for GenericErrorResponse.
type GenericErrorResponse struct {
	Code      string `json:"Code"`
	ErrorCode string `json:"ErrorCode"`
	Message   string `json:"Message"`
	RequestId string `json:"RequestId"`
}

// PropertiesInfoResponse defines model for PropertiesInfoResponse.
type PropertiesInfoResponse struct {
	Data      *[]PropertyInfoData `json:"data,omitempty"`
	RequestId string              `json:"requestId"`
}

// PropertyInfoData defines model for PropertyInfoData.
type PropertyInfoData struct {
	// PropertyRating This field can be used to provide a property score or rating on the channel. It is used together with the propertyRatingScale to indicate the score and scale. Example 4 out of 5 where 4 is the rating and 5 is the scale. This value cannot be bigger than the propertyRatingScale.
	PropertyRating *float32 `json:"propertyRating,omitempty"`

	// PropertyStatus Field that indicates the status of a property on the channel. Accepted values are "active" for a property that is opened and bookable, "inactive" for a property that is no longer open and bookable, "inactive_checks" when a property is currently closed but will be opened after optional checks are done, "inactive_temporary" when a property was opened but it is now closed for a short period of time while resolving an issue, "inactive_duplicate" when a property already exists on the channel with a different property id or provider.
	PropertyStatus *PropertyInfoDataPropertyStatus `json:"propertyStatus,omitempty"`

	// PropertyStatusNote This field can be used to provide more information as to why a property has a specific status on the channel.
	PropertyStatusNote *string `json:"propertyStatusNote,omitempty"`

	// PropertyUrl This field can be used to provide the property direct url on the channel.
	PropertyUrl *string `json:"propertyUrl,omitempty"`

	// RatingScale This field can be used to indicate the scale used for the property rating. It is required if channelPropertyRating field has a value.
	RatingScale *int `json:"ratingScale,omitempty"`
}

// PropertyInfoDataPropertyStatus Field that indicates the status of a property on the channel. Accepted values are "active" for a property that is opened and bookable, "inactive" for a property that is no longer open and bookable, "inactive_checks" when a property is currently closed but will be opened after optional checks are done, "inactive_temporary" when a property was opened but it is now closed for a short period of time while resolving an issue, "inactive_duplicate" when a property already exists on the channel with a different property id or provider.
type PropertyInfoDataPropertyStatus string

// PropertyInfoResponse defines model for PropertyInfoResponse.
type PropertyInfoResponse struct {
	Data      *PropertyInfoData `json:"data,omitempty"`
	RequestId string            `json:"requestId"`
}

// CreateUpdatePropertyInfoByIdJSONRequestBody defines body for CreateUpdatePropertyInfoById for application/json ContentType.
type CreateUpdatePropertyInfoByIdJSONRequestBody = PropertyInfoData
