/*
 * swagger example API
 *
 * API to demo swagger
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 *
 * Hooray! It's out custom header
 *
 */
package java

import (
	"log"
	"net/http"

	service "github.com/grbit/swagger-example/internal/java/handlers"
	. "github.com/grbit/swagger-example/pkg/java/models"

	"github.com/goccy/go-json"
	"github.com/gorilla/mux"
	"golang.org/x/xerrors"
)

func CreateUpdatePropertyInfoById(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	// pathParams
	propertyId := mux.Vars(r)["propertyId"]
	// body params
	var body PropertyInfoData

	decoder := json.NewDecoder(r.Body)

	err := decoder.Decode(&body)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(xerrors.Errorf("BadRequest: %w", err).Error()))

		return
	}

	var response PropertyInfoResponse
	response, responseErr := service.HandleCreateUpdatePropertyInfoById(r, body, propertyId)

	if responseErr != nil {
		err := xerrors.Errorf("InternalServerError: %w", responseErr)
		log.Println(err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(err.Error()))

		return
	}

	w.WriteHeader(http.StatusOK)
	payload, _ := json.Marshal(response)
	w.Write(payload)
}

func GetPropertiesInfo(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	var response PropertiesInfoResponse
	response, responseErr := service.HandleGetPropertiesInfo(r)

	if responseErr != nil {
		err := xerrors.Errorf("InternalServerError: %w", responseErr)
		log.Println("InternalServerError", err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(err.Error()))

		return
	}

	payload, _ := json.Marshal(response)
	w.WriteHeader(http.StatusOK)
	w.Write(payload)
}

func GetPropertyInfoById(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	// pathParams
	propertyId := mux.Vars(r)["propertyId"]
	var response PropertyInfoResponse
	response, responseErr := service.HandleGetPropertyInfoById(r, propertyId)

	if responseErr != nil {
		err := xerrors.Errorf("InternalServerError: %w", responseErr)
		log.Println("InternalServerError", err.Error())
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(err.Error()))

		return
	}

	payload, _ := json.Marshal(response)
	w.WriteHeader(http.StatusOK)
	w.Write(payload)
}

func extractQueryParam(request *http.Request, param string) *string {
	query := request.URL.Query()
	value, ok := query[param]

	if ok && len(value[0]) > 0 {
		return &value[0]
	}

	return nil
}
