// Package oapi_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi_client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	. "github.com/grbit/swagger-example/pkg/codegen/models"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetPropertiesInfo request
	GetPropertiesInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPropertyInfoById request
	GetPropertyInfoById(ctx context.Context, propertyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUpdatePropertyInfoById request with any body
	CreateUpdatePropertyInfoByIdWithBody(ctx context.Context, propertyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUpdatePropertyInfoById(ctx context.Context, propertyId string, body CreateUpdatePropertyInfoByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetPropertiesInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPropertiesInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPropertyInfoById(ctx context.Context, propertyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPropertyInfoByIdRequest(c.Server, propertyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUpdatePropertyInfoByIdWithBody(ctx context.Context, propertyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUpdatePropertyInfoByIdRequestWithBody(c.Server, propertyId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUpdatePropertyInfoById(ctx context.Context, propertyId string, body CreateUpdatePropertyInfoByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUpdatePropertyInfoByIdRequest(c.Server, propertyId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPropertiesInfoRequest generates requests for GetPropertiesInfo
func NewGetPropertiesInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/property")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPropertyInfoByIdRequest generates requests for GetPropertyInfoById
func NewGetPropertyInfoByIdRequest(server string, propertyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "propertyId", runtime.ParamLocationPath, propertyId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/property/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUpdatePropertyInfoByIdRequest calls the generic CreateUpdatePropertyInfoById builder with application/json body
func NewCreateUpdatePropertyInfoByIdRequest(server string, propertyId string, body CreateUpdatePropertyInfoByIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUpdatePropertyInfoByIdRequestWithBody(server, propertyId, "application/json", bodyReader)
}

// NewCreateUpdatePropertyInfoByIdRequestWithBody generates requests for CreateUpdatePropertyInfoById with any type of body
func NewCreateUpdatePropertyInfoByIdRequestWithBody(server string, propertyId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "propertyId", runtime.ParamLocationPath, propertyId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/property/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetPropertiesInfo request
	GetPropertiesInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetPropertiesInfoResponse, error)

	// GetPropertyInfoById request
	GetPropertyInfoByIdWithResponse(ctx context.Context, propertyId string, reqEditors ...RequestEditorFn) (*GetPropertyInfoByIdResponse, error)

	// CreateUpdatePropertyInfoById request with any body
	CreateUpdatePropertyInfoByIdWithBodyWithResponse(ctx context.Context, propertyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUpdatePropertyInfoByIdResponse, error)

	CreateUpdatePropertyInfoByIdWithResponse(ctx context.Context, propertyId string, body CreateUpdatePropertyInfoByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUpdatePropertyInfoByIdResponse, error)
}

type GetPropertiesInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PropertiesInfoResponse
	JSON400      *GenericErrorResponse
	JSON500      *GenericErrorResponse
	JSON501      *GenericErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPropertiesInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPropertiesInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPropertyInfoByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PropertyInfoResponse
	JSON400      *GenericErrorResponse
	JSON500      *GenericErrorResponse
	JSON501      *GenericErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPropertyInfoByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPropertyInfoByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUpdatePropertyInfoByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PropertyInfoResponse
	JSON400      *GenericErrorResponse
	JSON500      *GenericErrorResponse
	JSON501      *GenericErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateUpdatePropertyInfoByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUpdatePropertyInfoByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetPropertiesInfoWithResponse request returning *GetPropertiesInfoResponse
func (c *ClientWithResponses) GetPropertiesInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetPropertiesInfoResponse, error) {
	rsp, err := c.GetPropertiesInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPropertiesInfoResponse(rsp)
}

// GetPropertyInfoByIdWithResponse request returning *GetPropertyInfoByIdResponse
func (c *ClientWithResponses) GetPropertyInfoByIdWithResponse(ctx context.Context, propertyId string, reqEditors ...RequestEditorFn) (*GetPropertyInfoByIdResponse, error) {
	rsp, err := c.GetPropertyInfoById(ctx, propertyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPropertyInfoByIdResponse(rsp)
}

// CreateUpdatePropertyInfoByIdWithBodyWithResponse request with arbitrary body returning *CreateUpdatePropertyInfoByIdResponse
func (c *ClientWithResponses) CreateUpdatePropertyInfoByIdWithBodyWithResponse(ctx context.Context, propertyId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUpdatePropertyInfoByIdResponse, error) {
	rsp, err := c.CreateUpdatePropertyInfoByIdWithBody(ctx, propertyId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUpdatePropertyInfoByIdResponse(rsp)
}

func (c *ClientWithResponses) CreateUpdatePropertyInfoByIdWithResponse(ctx context.Context, propertyId string, body CreateUpdatePropertyInfoByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUpdatePropertyInfoByIdResponse, error) {
	rsp, err := c.CreateUpdatePropertyInfoById(ctx, propertyId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUpdatePropertyInfoByIdResponse(rsp)
}

// ParseGetPropertiesInfoResponse parses an HTTP response from a GetPropertiesInfoWithResponse call
func ParseGetPropertiesInfoResponse(rsp *http.Response) (*GetPropertiesInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPropertiesInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PropertiesInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	}

	return response, nil
}

// ParseGetPropertyInfoByIdResponse parses an HTTP response from a GetPropertyInfoByIdWithResponse call
func ParseGetPropertyInfoByIdResponse(rsp *http.Response) (*GetPropertyInfoByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPropertyInfoByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PropertyInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	}

	return response, nil
}

// ParseCreateUpdatePropertyInfoByIdResponse parses an HTTP response from a CreateUpdatePropertyInfoByIdWithResponse call
func ParseCreateUpdatePropertyInfoByIdResponse(rsp *http.Response) (*CreateUpdatePropertyInfoByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUpdatePropertyInfoByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PropertyInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest GenericErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	}

	return response, nil
}
