// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// AddAccUpdaterURL generates an URL for the add acc updater operation
type AddAccUpdaterURL struct {
	AccountID int64
	ClientID  *int64
	Force     *bool
	UserID    int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AddAccUpdaterURL) WithBasePath(bp string) *AddAccUpdaterURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AddAccUpdaterURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *AddAccUpdaterURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1/accounts"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	accountIDQ := swag.FormatInt64(o.AccountID)
	if accountIDQ != "" {
		qs.Set("account_id", accountIDQ)
	}

	var clientIDQ string
	if o.ClientID != nil {
		clientIDQ = swag.FormatInt64(*o.ClientID)
	}
	if clientIDQ != "" {
		qs.Set("client_id", clientIDQ)
	}

	var forceQ string
	if o.Force != nil {
		forceQ = swag.FormatBool(*o.Force)
	}
	if forceQ != "" {
		qs.Set("force", forceQ)
	}

	userIDQ := swag.FormatInt64(o.UserID)
	if userIDQ != "" {
		qs.Set("user_id", userIDQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *AddAccUpdaterURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *AddAccUpdaterURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *AddAccUpdaterURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on AddAccUpdaterURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on AddAccUpdaterURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *AddAccUpdaterURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
