// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime"
)

// AddAccUpdaterOKCode is the HTTP code returned for type AddAccUpdaterOK
const AddAccUpdaterOKCode int = 200

/*
AddAccUpdaterOK success 200

swagger:response addAccUpdaterOK
*/
type AddAccUpdaterOK struct {

	/*
	  In: Body
	*/
	Payload *model.Ok `json:"body,omitempty"`
}

// NewAddAccUpdaterOK creates AddAccUpdaterOK with default headers values
func NewAddAccUpdaterOK() *AddAccUpdaterOK {

	return &AddAccUpdaterOK{}
}

// WithPayload adds the payload to the add acc updater o k response
func (o *AddAccUpdaterOK) WithPayload(payload *model.Ok) *AddAccUpdaterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add acc updater o k response
func (o *AddAccUpdaterOK) SetPayload(payload *model.Ok) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddAccUpdaterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddAccUpdaterCreatedCode is the HTTP code returned for type AddAccUpdaterCreated
const AddAccUpdaterCreatedCode int = 201

/*
AddAccUpdaterCreated created 201

swagger:response addAccUpdaterCreated
*/
type AddAccUpdaterCreated struct {

	/*
	  In: Body
	*/
	Payload *model.Ok `json:"body,omitempty"`
}

// NewAddAccUpdaterCreated creates AddAccUpdaterCreated with default headers values
func NewAddAccUpdaterCreated() *AddAccUpdaterCreated {

	return &AddAccUpdaterCreated{}
}

// WithPayload adds the payload to the add acc updater created response
func (o *AddAccUpdaterCreated) WithPayload(payload *model.Ok) *AddAccUpdaterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add acc updater created response
func (o *AddAccUpdaterCreated) SetPayload(payload *model.Ok) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddAccUpdaterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddAccUpdaterBadRequestCode is the HTTP code returned for type AddAccUpdaterBadRequest
const AddAccUpdaterBadRequestCode int = 400

/*
AddAccUpdaterBadRequest bad request 400

swagger:response addAccUpdaterBadRequest
*/
type AddAccUpdaterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewAddAccUpdaterBadRequest creates AddAccUpdaterBadRequest with default headers values
func NewAddAccUpdaterBadRequest() *AddAccUpdaterBadRequest {

	return &AddAccUpdaterBadRequest{}
}

// WithPayload adds the payload to the add acc updater bad request response
func (o *AddAccUpdaterBadRequest) WithPayload(payload *model.ErrorResponse) *AddAccUpdaterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add acc updater bad request response
func (o *AddAccUpdaterBadRequest) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddAccUpdaterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddAccUpdaterInternalServerErrorCode is the HTTP code returned for type AddAccUpdaterInternalServerError
const AddAccUpdaterInternalServerErrorCode int = 500

/*
AddAccUpdaterInternalServerError internal server error 500

swagger:response addAccUpdaterInternalServerError
*/
type AddAccUpdaterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewAddAccUpdaterInternalServerError creates AddAccUpdaterInternalServerError with default headers values
func NewAddAccUpdaterInternalServerError() *AddAccUpdaterInternalServerError {

	return &AddAccUpdaterInternalServerError{}
}

// WithPayload adds the payload to the add acc updater internal server error response
func (o *AddAccUpdaterInternalServerError) WithPayload(payload *model.ErrorResponse) *AddAccUpdaterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add acc updater internal server error response
func (o *AddAccUpdaterInternalServerError) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddAccUpdaterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
