// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime/middleware"
)

// DelAccUpdaterHandlerFunc turns a function with the right signature into a del acc updater handler
type DelAccUpdaterHandlerFunc func(DelAccUpdaterParams, *model.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DelAccUpdaterHandlerFunc) Handle(params DelAccUpdaterParams, principal *model.Principal) middleware.Responder {
	return fn(params, principal)
}

// DelAccUpdaterHandler interface for that can handle valid del acc updater params
type DelAccUpdaterHandler interface {
	Handle(DelAccUpdaterParams, *model.Principal) middleware.Responder
}

// NewDelAccUpdater creates a new http.Handler for the del acc updater operation
func NewDelAccUpdater(ctx *middleware.Context, handler DelAccUpdaterHandler) *DelAccUpdater {
	return &DelAccUpdater{Context: ctx, Handler: handler}
}

/*
	DelAccUpdater swagger:route DELETE /{account_id} delAccUpdater

Delete account from loading queue and stop regularly updates.

	Note: in --loader-acc-list-upd-timeout (default 600s) account list will be updated from cabinets service, if account presented in service, new update will be started.
*/
type DelAccUpdater struct {
	Context *middleware.Context
	Handler DelAccUpdaterHandler
}

func (o *DelAccUpdater) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDelAccUpdaterParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *model.Principal
	if uprinc != nil {
		principal = uprinc.(*model.Principal) // this is really a model.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
