// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime"
)

// DelAccUpdaterOKCode is the HTTP code returned for type DelAccUpdaterOK
const DelAccUpdaterOKCode int = 200

/*
DelAccUpdaterOK success 200

swagger:response delAccUpdaterOK
*/
type DelAccUpdaterOK struct {

	/*
	  In: Body
	*/
	Payload *model.Ok `json:"body,omitempty"`
}

// NewDelAccUpdaterOK creates DelAccUpdaterOK with default headers values
func NewDelAccUpdaterOK() *DelAccUpdaterOK {

	return &DelAccUpdaterOK{}
}

// WithPayload adds the payload to the del acc updater o k response
func (o *DelAccUpdaterOK) WithPayload(payload *model.Ok) *DelAccUpdaterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the del acc updater o k response
func (o *DelAccUpdaterOK) SetPayload(payload *model.Ok) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DelAccUpdaterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DelAccUpdaterBadRequestCode is the HTTP code returned for type DelAccUpdaterBadRequest
const DelAccUpdaterBadRequestCode int = 400

/*
DelAccUpdaterBadRequest bad request 400

swagger:response delAccUpdaterBadRequest
*/
type DelAccUpdaterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewDelAccUpdaterBadRequest creates DelAccUpdaterBadRequest with default headers values
func NewDelAccUpdaterBadRequest() *DelAccUpdaterBadRequest {

	return &DelAccUpdaterBadRequest{}
}

// WithPayload adds the payload to the del acc updater bad request response
func (o *DelAccUpdaterBadRequest) WithPayload(payload *model.ErrorResponse) *DelAccUpdaterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the del acc updater bad request response
func (o *DelAccUpdaterBadRequest) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DelAccUpdaterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DelAccUpdaterInternalServerErrorCode is the HTTP code returned for type DelAccUpdaterInternalServerError
const DelAccUpdaterInternalServerErrorCode int = 500

/*
DelAccUpdaterInternalServerError internal server error 500

swagger:response delAccUpdaterInternalServerError
*/
type DelAccUpdaterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewDelAccUpdaterInternalServerError creates DelAccUpdaterInternalServerError with default headers values
func NewDelAccUpdaterInternalServerError() *DelAccUpdaterInternalServerError {

	return &DelAccUpdaterInternalServerError{}
}

// WithPayload adds the payload to the del acc updater internal server error response
func (o *DelAccUpdaterInternalServerError) WithPayload(payload *model.ErrorResponse) *DelAccUpdaterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the del acc updater internal server error response
func (o *DelAccUpdaterInternalServerError) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DelAccUpdaterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
