// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime"
)

// GetAdsStatsOKCode is the HTTP code returned for type GetAdsStatsOK
const GetAdsStatsOKCode int = 200

/*
GetAdsStatsOK pages of Ad

swagger:response getAdsStatsOK
*/
type GetAdsStatsOK struct {

	/*
	  In: Body
	*/
	Payload *GetAdsStatsOKBody `json:"body,omitempty"`
}

// NewGetAdsStatsOK creates GetAdsStatsOK with default headers values
func NewGetAdsStatsOK() *GetAdsStatsOK {

	return &GetAdsStatsOK{}
}

// WithPayload adds the payload to the get ads stats o k response
func (o *GetAdsStatsOK) WithPayload(payload *GetAdsStatsOKBody) *GetAdsStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ads stats o k response
func (o *GetAdsStatsOK) SetPayload(payload *GetAdsStatsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdsStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdsStatsBadRequestCode is the HTTP code returned for type GetAdsStatsBadRequest
const GetAdsStatsBadRequestCode int = 400

/*
GetAdsStatsBadRequest bad request 400

swagger:response getAdsStatsBadRequest
*/
type GetAdsStatsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewGetAdsStatsBadRequest creates GetAdsStatsBadRequest with default headers values
func NewGetAdsStatsBadRequest() *GetAdsStatsBadRequest {

	return &GetAdsStatsBadRequest{}
}

// WithPayload adds the payload to the get ads stats bad request response
func (o *GetAdsStatsBadRequest) WithPayload(payload *model.ErrorResponse) *GetAdsStatsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ads stats bad request response
func (o *GetAdsStatsBadRequest) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdsStatsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdsStatsUnauthorizedCode is the HTTP code returned for type GetAdsStatsUnauthorized
const GetAdsStatsUnauthorizedCode int = 401

/*
GetAdsStatsUnauthorized unauthorized 400

swagger:response getAdsStatsUnauthorized
*/
type GetAdsStatsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewGetAdsStatsUnauthorized creates GetAdsStatsUnauthorized with default headers values
func NewGetAdsStatsUnauthorized() *GetAdsStatsUnauthorized {

	return &GetAdsStatsUnauthorized{}
}

// WithPayload adds the payload to the get ads stats unauthorized response
func (o *GetAdsStatsUnauthorized) WithPayload(payload *model.ErrorResponse) *GetAdsStatsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ads stats unauthorized response
func (o *GetAdsStatsUnauthorized) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdsStatsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdsStatsInternalServerErrorCode is the HTTP code returned for type GetAdsStatsInternalServerError
const GetAdsStatsInternalServerErrorCode int = 500

/*
GetAdsStatsInternalServerError internal server error 500

swagger:response getAdsStatsInternalServerError
*/
type GetAdsStatsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewGetAdsStatsInternalServerError creates GetAdsStatsInternalServerError with default headers values
func NewGetAdsStatsInternalServerError() *GetAdsStatsInternalServerError {

	return &GetAdsStatsInternalServerError{}
}

// WithPayload adds the payload to the get ads stats internal server error response
func (o *GetAdsStatsInternalServerError) WithPayload(payload *model.ErrorResponse) *GetAdsStatsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ads stats internal server error response
func (o *GetAdsStatsInternalServerError) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdsStatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
