// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetCampaignsStatsHandlerFunc turns a function with the right signature into a get campaigns stats handler
type GetCampaignsStatsHandlerFunc func(GetCampaignsStatsParams, *model.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCampaignsStatsHandlerFunc) Handle(params GetCampaignsStatsParams, principal *model.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCampaignsStatsHandler interface for that can handle valid get campaigns stats params
type GetCampaignsStatsHandler interface {
	Handle(GetCampaignsStatsParams, *model.Principal) middleware.Responder
}

// NewGetCampaignsStats creates a new http.Handler for the get campaigns stats operation
func NewGetCampaignsStats(ctx *middleware.Context, handler GetCampaignsStatsHandler) *GetCampaignsStats {
	return &GetCampaignsStats{Context: ctx, Handler: handler}
}

/*
	GetCampaignsStats swagger:route GET /{account_id}/campaigns getCampaignsStats

Gives array of stats for set time period. If updatedSince set, then reutrns only stats updated after set time
*/
type GetCampaignsStats struct {
	Context *middleware.Context
	Handler GetCampaignsStatsHandler
}

func (o *GetCampaignsStats) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCampaignsStatsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *model.Principal
	if uprinc != nil {
		principal = uprinc.(*model.Principal) // this is really a model.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetCampaignsStatsOKBody get campaigns stats o k body
//
// swagger:model GetCampaignsStatsOKBody
type GetCampaignsStatsOKBody struct {

	// campaigns
	Campaigns *model.CampaignStatsPage `json:"campaigns,omitempty"`
}

// Validate validates this get campaigns stats o k body
func (o *GetCampaignsStatsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCampaigns(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCampaignsStatsOKBody) validateCampaigns(formats strfmt.Registry) error {
	if swag.IsZero(o.Campaigns) { // not required
		return nil
	}

	if o.Campaigns != nil {
		if err := o.Campaigns.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCampaignsStatsOK" + "." + "campaigns")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getCampaignsStatsOK" + "." + "campaigns")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get campaigns stats o k body based on the context it is used
func (o *GetCampaignsStatsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateCampaigns(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCampaignsStatsOKBody) contextValidateCampaigns(ctx context.Context, formats strfmt.Registry) error {

	if o.Campaigns != nil {
		if err := o.Campaigns.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCampaignsStatsOK" + "." + "campaigns")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getCampaignsStatsOK" + "." + "campaigns")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCampaignsStatsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCampaignsStatsOKBody) UnmarshalBinary(b []byte) error {
	var res GetCampaignsStatsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
