// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime"
)

// GetCampaignsStatsOKCode is the HTTP code returned for type GetCampaignsStatsOK
const GetCampaignsStatsOKCode int = 200

/*
GetCampaignsStatsOK pages of Campaign

swagger:response getCampaignsStatsOK
*/
type GetCampaignsStatsOK struct {

	/*
	  In: Body
	*/
	Payload *GetCampaignsStatsOKBody `json:"body,omitempty"`
}

// NewGetCampaignsStatsOK creates GetCampaignsStatsOK with default headers values
func NewGetCampaignsStatsOK() *GetCampaignsStatsOK {

	return &GetCampaignsStatsOK{}
}

// WithPayload adds the payload to the get campaigns stats o k response
func (o *GetCampaignsStatsOK) WithPayload(payload *GetCampaignsStatsOKBody) *GetCampaignsStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get campaigns stats o k response
func (o *GetCampaignsStatsOK) SetPayload(payload *GetCampaignsStatsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCampaignsStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCampaignsStatsBadRequestCode is the HTTP code returned for type GetCampaignsStatsBadRequest
const GetCampaignsStatsBadRequestCode int = 400

/*
GetCampaignsStatsBadRequest bad request 400

swagger:response getCampaignsStatsBadRequest
*/
type GetCampaignsStatsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewGetCampaignsStatsBadRequest creates GetCampaignsStatsBadRequest with default headers values
func NewGetCampaignsStatsBadRequest() *GetCampaignsStatsBadRequest {

	return &GetCampaignsStatsBadRequest{}
}

// WithPayload adds the payload to the get campaigns stats bad request response
func (o *GetCampaignsStatsBadRequest) WithPayload(payload *model.ErrorResponse) *GetCampaignsStatsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get campaigns stats bad request response
func (o *GetCampaignsStatsBadRequest) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCampaignsStatsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCampaignsStatsUnauthorizedCode is the HTTP code returned for type GetCampaignsStatsUnauthorized
const GetCampaignsStatsUnauthorizedCode int = 401

/*
GetCampaignsStatsUnauthorized unauthorized 400

swagger:response getCampaignsStatsUnauthorized
*/
type GetCampaignsStatsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewGetCampaignsStatsUnauthorized creates GetCampaignsStatsUnauthorized with default headers values
func NewGetCampaignsStatsUnauthorized() *GetCampaignsStatsUnauthorized {

	return &GetCampaignsStatsUnauthorized{}
}

// WithPayload adds the payload to the get campaigns stats unauthorized response
func (o *GetCampaignsStatsUnauthorized) WithPayload(payload *model.ErrorResponse) *GetCampaignsStatsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get campaigns stats unauthorized response
func (o *GetCampaignsStatsUnauthorized) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCampaignsStatsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCampaignsStatsInternalServerErrorCode is the HTTP code returned for type GetCampaignsStatsInternalServerError
const GetCampaignsStatsInternalServerErrorCode int = 500

/*
GetCampaignsStatsInternalServerError internal server error 500

swagger:response getCampaignsStatsInternalServerError
*/
type GetCampaignsStatsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.ErrorResponse `json:"body,omitempty"`
}

// NewGetCampaignsStatsInternalServerError creates GetCampaignsStatsInternalServerError with default headers values
func NewGetCampaignsStatsInternalServerError() *GetCampaignsStatsInternalServerError {

	return &GetCampaignsStatsInternalServerError{}
}

// WithPayload adds the payload to the get campaigns stats internal server error response
func (o *GetCampaignsStatsInternalServerError) WithPayload(payload *model.ErrorResponse) *GetCampaignsStatsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get campaigns stats internal server error response
func (o *GetCampaignsStatsInternalServerError) SetPayload(payload *model.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCampaignsStatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
