// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddAccUpdaterReader is a Reader for the AddAccUpdater structure.
type AddAccUpdaterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddAccUpdaterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddAccUpdaterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewAddAccUpdaterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddAccUpdaterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddAccUpdaterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddAccUpdaterOK creates a AddAccUpdaterOK with default headers values
func NewAddAccUpdaterOK() *AddAccUpdaterOK {
	return &AddAccUpdaterOK{}
}

/*
AddAccUpdaterOK describes a response with status code 200, with default header values.

success 200
*/
type AddAccUpdaterOK struct {
	Payload *model.Ok
}

// IsSuccess returns true when this add acc updater o k response has a 2xx status code
func (o *AddAccUpdaterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add acc updater o k response has a 3xx status code
func (o *AddAccUpdaterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add acc updater o k response has a 4xx status code
func (o *AddAccUpdaterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add acc updater o k response has a 5xx status code
func (o *AddAccUpdaterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add acc updater o k response a status code equal to that given
func (o *AddAccUpdaterOK) IsCode(code int) bool {
	return code == 200
}

func (o *AddAccUpdaterOK) Error() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterOK  %+v", 200, o.Payload)
}

func (o *AddAccUpdaterOK) String() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterOK  %+v", 200, o.Payload)
}

func (o *AddAccUpdaterOK) GetPayload() *model.Ok {
	return o.Payload
}

func (o *AddAccUpdaterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Ok)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddAccUpdaterCreated creates a AddAccUpdaterCreated with default headers values
func NewAddAccUpdaterCreated() *AddAccUpdaterCreated {
	return &AddAccUpdaterCreated{}
}

/*
AddAccUpdaterCreated describes a response with status code 201, with default header values.

created 201
*/
type AddAccUpdaterCreated struct {
	Payload *model.Ok
}

// IsSuccess returns true when this add acc updater created response has a 2xx status code
func (o *AddAccUpdaterCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add acc updater created response has a 3xx status code
func (o *AddAccUpdaterCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add acc updater created response has a 4xx status code
func (o *AddAccUpdaterCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this add acc updater created response has a 5xx status code
func (o *AddAccUpdaterCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this add acc updater created response a status code equal to that given
func (o *AddAccUpdaterCreated) IsCode(code int) bool {
	return code == 201
}

func (o *AddAccUpdaterCreated) Error() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterCreated  %+v", 201, o.Payload)
}

func (o *AddAccUpdaterCreated) String() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterCreated  %+v", 201, o.Payload)
}

func (o *AddAccUpdaterCreated) GetPayload() *model.Ok {
	return o.Payload
}

func (o *AddAccUpdaterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Ok)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddAccUpdaterBadRequest creates a AddAccUpdaterBadRequest with default headers values
func NewAddAccUpdaterBadRequest() *AddAccUpdaterBadRequest {
	return &AddAccUpdaterBadRequest{}
}

/*
AddAccUpdaterBadRequest describes a response with status code 400, with default header values.

bad request 400
*/
type AddAccUpdaterBadRequest struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this add acc updater bad request response has a 2xx status code
func (o *AddAccUpdaterBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add acc updater bad request response has a 3xx status code
func (o *AddAccUpdaterBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add acc updater bad request response has a 4xx status code
func (o *AddAccUpdaterBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this add acc updater bad request response has a 5xx status code
func (o *AddAccUpdaterBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this add acc updater bad request response a status code equal to that given
func (o *AddAccUpdaterBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *AddAccUpdaterBadRequest) Error() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterBadRequest  %+v", 400, o.Payload)
}

func (o *AddAccUpdaterBadRequest) String() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterBadRequest  %+v", 400, o.Payload)
}

func (o *AddAccUpdaterBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *AddAccUpdaterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddAccUpdaterInternalServerError creates a AddAccUpdaterInternalServerError with default headers values
func NewAddAccUpdaterInternalServerError() *AddAccUpdaterInternalServerError {
	return &AddAccUpdaterInternalServerError{}
}

/*
AddAccUpdaterInternalServerError describes a response with status code 500, with default header values.

internal server error 500
*/
type AddAccUpdaterInternalServerError struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this add acc updater internal server error response has a 2xx status code
func (o *AddAccUpdaterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add acc updater internal server error response has a 3xx status code
func (o *AddAccUpdaterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add acc updater internal server error response has a 4xx status code
func (o *AddAccUpdaterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this add acc updater internal server error response has a 5xx status code
func (o *AddAccUpdaterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this add acc updater internal server error response a status code equal to that given
func (o *AddAccUpdaterInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *AddAccUpdaterInternalServerError) Error() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterInternalServerError  %+v", 500, o.Payload)
}

func (o *AddAccUpdaterInternalServerError) String() string {
	return fmt.Sprintf("[POST /][%d] addAccUpdaterInternalServerError  %+v", 500, o.Payload)
}

func (o *AddAccUpdaterInternalServerError) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *AddAccUpdaterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
