// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DelAccUpdaterReader is a Reader for the DelAccUpdater structure.
type DelAccUpdaterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelAccUpdaterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDelAccUpdaterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDelAccUpdaterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDelAccUpdaterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDelAccUpdaterOK creates a DelAccUpdaterOK with default headers values
func NewDelAccUpdaterOK() *DelAccUpdaterOK {
	return &DelAccUpdaterOK{}
}

/*
DelAccUpdaterOK describes a response with status code 200, with default header values.

success 200
*/
type DelAccUpdaterOK struct {
	Payload *model.Ok
}

// IsSuccess returns true when this del acc updater o k response has a 2xx status code
func (o *DelAccUpdaterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this del acc updater o k response has a 3xx status code
func (o *DelAccUpdaterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del acc updater o k response has a 4xx status code
func (o *DelAccUpdaterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this del acc updater o k response has a 5xx status code
func (o *DelAccUpdaterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this del acc updater o k response a status code equal to that given
func (o *DelAccUpdaterOK) IsCode(code int) bool {
	return code == 200
}

func (o *DelAccUpdaterOK) Error() string {
	return fmt.Sprintf("[DELETE /{account_id}][%d] delAccUpdaterOK  %+v", 200, o.Payload)
}

func (o *DelAccUpdaterOK) String() string {
	return fmt.Sprintf("[DELETE /{account_id}][%d] delAccUpdaterOK  %+v", 200, o.Payload)
}

func (o *DelAccUpdaterOK) GetPayload() *model.Ok {
	return o.Payload
}

func (o *DelAccUpdaterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Ok)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDelAccUpdaterBadRequest creates a DelAccUpdaterBadRequest with default headers values
func NewDelAccUpdaterBadRequest() *DelAccUpdaterBadRequest {
	return &DelAccUpdaterBadRequest{}
}

/*
DelAccUpdaterBadRequest describes a response with status code 400, with default header values.

bad request 400
*/
type DelAccUpdaterBadRequest struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this del acc updater bad request response has a 2xx status code
func (o *DelAccUpdaterBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del acc updater bad request response has a 3xx status code
func (o *DelAccUpdaterBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del acc updater bad request response has a 4xx status code
func (o *DelAccUpdaterBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this del acc updater bad request response has a 5xx status code
func (o *DelAccUpdaterBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this del acc updater bad request response a status code equal to that given
func (o *DelAccUpdaterBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DelAccUpdaterBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /{account_id}][%d] delAccUpdaterBadRequest  %+v", 400, o.Payload)
}

func (o *DelAccUpdaterBadRequest) String() string {
	return fmt.Sprintf("[DELETE /{account_id}][%d] delAccUpdaterBadRequest  %+v", 400, o.Payload)
}

func (o *DelAccUpdaterBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *DelAccUpdaterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDelAccUpdaterInternalServerError creates a DelAccUpdaterInternalServerError with default headers values
func NewDelAccUpdaterInternalServerError() *DelAccUpdaterInternalServerError {
	return &DelAccUpdaterInternalServerError{}
}

/*
DelAccUpdaterInternalServerError describes a response with status code 500, with default header values.

internal server error 500
*/
type DelAccUpdaterInternalServerError struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this del acc updater internal server error response has a 2xx status code
func (o *DelAccUpdaterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del acc updater internal server error response has a 3xx status code
func (o *DelAccUpdaterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del acc updater internal server error response has a 4xx status code
func (o *DelAccUpdaterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this del acc updater internal server error response has a 5xx status code
func (o *DelAccUpdaterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this del acc updater internal server error response a status code equal to that given
func (o *DelAccUpdaterInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DelAccUpdaterInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /{account_id}][%d] delAccUpdaterInternalServerError  %+v", 500, o.Payload)
}

func (o *DelAccUpdaterInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /{account_id}][%d] delAccUpdaterInternalServerError  %+v", 500, o.Payload)
}

func (o *DelAccUpdaterInternalServerError) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *DelAccUpdaterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
