// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/grbit/swagger-example/pkg/sw2/model"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAdsStatsReader is a Reader for the GetAdsStats structure.
type GetAdsStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAdsStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAdsStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAdsStatsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAdsStatsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAdsStatsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAdsStatsOK creates a GetAdsStatsOK with default headers values
func NewGetAdsStatsOK() *GetAdsStatsOK {
	return &GetAdsStatsOK{}
}

/*
GetAdsStatsOK describes a response with status code 200, with default header values.

pages of Ad
*/
type GetAdsStatsOK struct {
	Payload *GetAdsStatsOKBody
}

// IsSuccess returns true when this get ads stats o k response has a 2xx status code
func (o *GetAdsStatsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ads stats o k response has a 3xx status code
func (o *GetAdsStatsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ads stats o k response has a 4xx status code
func (o *GetAdsStatsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ads stats o k response has a 5xx status code
func (o *GetAdsStatsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ads stats o k response a status code equal to that given
func (o *GetAdsStatsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAdsStatsOK) Error() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsOK  %+v", 200, o.Payload)
}

func (o *GetAdsStatsOK) String() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsOK  %+v", 200, o.Payload)
}

func (o *GetAdsStatsOK) GetPayload() *GetAdsStatsOKBody {
	return o.Payload
}

func (o *GetAdsStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAdsStatsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAdsStatsBadRequest creates a GetAdsStatsBadRequest with default headers values
func NewGetAdsStatsBadRequest() *GetAdsStatsBadRequest {
	return &GetAdsStatsBadRequest{}
}

/*
GetAdsStatsBadRequest describes a response with status code 400, with default header values.

bad request 400
*/
type GetAdsStatsBadRequest struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this get ads stats bad request response has a 2xx status code
func (o *GetAdsStatsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get ads stats bad request response has a 3xx status code
func (o *GetAdsStatsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ads stats bad request response has a 4xx status code
func (o *GetAdsStatsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get ads stats bad request response has a 5xx status code
func (o *GetAdsStatsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get ads stats bad request response a status code equal to that given
func (o *GetAdsStatsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetAdsStatsBadRequest) Error() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAdsStatsBadRequest) String() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAdsStatsBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *GetAdsStatsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAdsStatsUnauthorized creates a GetAdsStatsUnauthorized with default headers values
func NewGetAdsStatsUnauthorized() *GetAdsStatsUnauthorized {
	return &GetAdsStatsUnauthorized{}
}

/*
GetAdsStatsUnauthorized describes a response with status code 401, with default header values.

unauthorized 400
*/
type GetAdsStatsUnauthorized struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this get ads stats unauthorized response has a 2xx status code
func (o *GetAdsStatsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get ads stats unauthorized response has a 3xx status code
func (o *GetAdsStatsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ads stats unauthorized response has a 4xx status code
func (o *GetAdsStatsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get ads stats unauthorized response has a 5xx status code
func (o *GetAdsStatsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get ads stats unauthorized response a status code equal to that given
func (o *GetAdsStatsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetAdsStatsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAdsStatsUnauthorized) String() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAdsStatsUnauthorized) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *GetAdsStatsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAdsStatsInternalServerError creates a GetAdsStatsInternalServerError with default headers values
func NewGetAdsStatsInternalServerError() *GetAdsStatsInternalServerError {
	return &GetAdsStatsInternalServerError{}
}

/*
GetAdsStatsInternalServerError describes a response with status code 500, with default header values.

internal server error 500
*/
type GetAdsStatsInternalServerError struct {
	Payload *model.ErrorResponse
}

// IsSuccess returns true when this get ads stats internal server error response has a 2xx status code
func (o *GetAdsStatsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get ads stats internal server error response has a 3xx status code
func (o *GetAdsStatsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ads stats internal server error response has a 4xx status code
func (o *GetAdsStatsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ads stats internal server error response has a 5xx status code
func (o *GetAdsStatsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get ads stats internal server error response a status code equal to that given
func (o *GetAdsStatsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetAdsStatsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAdsStatsInternalServerError) String() string {
	return fmt.Sprintf("[GET /{account_id}/ads][%d] getAdsStatsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAdsStatsInternalServerError) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *GetAdsStatsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetAdsStatsOKBody get ads stats o k body
swagger:model GetAdsStatsOKBody
*/
type GetAdsStatsOKBody struct {

	// ads
	Ads *model.AdStatsPage `json:"ads,omitempty"`
}

// Validate validates this get ads stats o k body
func (o *GetAdsStatsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAdsStatsOKBody) validateAds(formats strfmt.Registry) error {
	if swag.IsZero(o.Ads) { // not required
		return nil
	}

	if o.Ads != nil {
		if err := o.Ads.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAdsStatsOK" + "." + "ads")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getAdsStatsOK" + "." + "ads")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get ads stats o k body based on the context it is used
func (o *GetAdsStatsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAds(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAdsStatsOKBody) contextValidateAds(ctx context.Context, formats strfmt.Registry) error {

	if o.Ads != nil {
		if err := o.Ads.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAdsStatsOK" + "." + "ads")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getAdsStatsOK" + "." + "ads")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAdsStatsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAdsStatsOKBody) UnmarshalBinary(b []byte) error {
	var res GetAdsStatsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
