// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCampaignsStatsParams creates a new GetCampaignsStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCampaignsStatsParams() *GetCampaignsStatsParams {
	return &GetCampaignsStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCampaignsStatsParamsWithTimeout creates a new GetCampaignsStatsParams object
// with the ability to set a timeout on a request.
func NewGetCampaignsStatsParamsWithTimeout(timeout time.Duration) *GetCampaignsStatsParams {
	return &GetCampaignsStatsParams{
		timeout: timeout,
	}
}

// NewGetCampaignsStatsParamsWithContext creates a new GetCampaignsStatsParams object
// with the ability to set a context for a request.
func NewGetCampaignsStatsParamsWithContext(ctx context.Context) *GetCampaignsStatsParams {
	return &GetCampaignsStatsParams{
		Context: ctx,
	}
}

// NewGetCampaignsStatsParamsWithHTTPClient creates a new GetCampaignsStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCampaignsStatsParamsWithHTTPClient(client *http.Client) *GetCampaignsStatsParams {
	return &GetCampaignsStatsParams{
		HTTPClient: client,
	}
}

/*
GetCampaignsStatsParams contains all the parameters to send to the API endpoint

	for the get campaigns stats operation.

	Typically these are written to a http.Request.
*/
type GetCampaignsStatsParams struct {

	// XRequestID.
	XRequestID string

	// AccountID.
	//
	// Format: int64
	AccountID int64

	// CampaignIds.
	CampaignIds []int64

	// ClientID.
	//
	// Format: int64
	ClientID *int64

	/* DateFrom.

	   If presented, return only statistics starting from presented date in Unixtime

	   Format: int64
	*/
	DateFrom *int64

	/* DateTo.

	   If presented, return only statistics up to presented date in Unixtime

	   Format: int64
	*/
	DateTo *int64

	/* Fields.

	   Enumeration wanted parameters of requested object
	*/
	Fields []string

	/* UpdatedSince.

	   If presented, return only statistics up to presented date in Unixtime

	   Format: int64
	*/
	UpdatedSince *int64

	// UserID.
	//
	// Format: int64
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get campaigns stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampaignsStatsParams) WithDefaults() *GetCampaignsStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get campaigns stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampaignsStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithTimeout(timeout time.Duration) *GetCampaignsStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithContext(ctx context.Context) *GetCampaignsStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithHTTPClient(client *http.Client) *GetCampaignsStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithXRequestID(xRequestID string) *GetCampaignsStatsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithAccountID adds the accountID to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithAccountID(accountID int64) *GetCampaignsStatsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetAccountID(accountID int64) {
	o.AccountID = accountID
}

// WithCampaignIds adds the campaignIds to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithCampaignIds(campaignIds []int64) *GetCampaignsStatsParams {
	o.SetCampaignIds(campaignIds)
	return o
}

// SetCampaignIds adds the campaignIds to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetCampaignIds(campaignIds []int64) {
	o.CampaignIds = campaignIds
}

// WithClientID adds the clientID to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithClientID(clientID *int64) *GetCampaignsStatsParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetClientID(clientID *int64) {
	o.ClientID = clientID
}

// WithDateFrom adds the dateFrom to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithDateFrom(dateFrom *int64) *GetCampaignsStatsParams {
	o.SetDateFrom(dateFrom)
	return o
}

// SetDateFrom adds the dateFrom to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetDateFrom(dateFrom *int64) {
	o.DateFrom = dateFrom
}

// WithDateTo adds the dateTo to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithDateTo(dateTo *int64) *GetCampaignsStatsParams {
	o.SetDateTo(dateTo)
	return o
}

// SetDateTo adds the dateTo to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetDateTo(dateTo *int64) {
	o.DateTo = dateTo
}

// WithFields adds the fields to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithFields(fields []string) *GetCampaignsStatsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithUpdatedSince adds the updatedSince to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithUpdatedSince(updatedSince *int64) *GetCampaignsStatsParams {
	o.SetUpdatedSince(updatedSince)
	return o
}

// SetUpdatedSince adds the updatedSince to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetUpdatedSince(updatedSince *int64) {
	o.UpdatedSince = updatedSince
}

// WithUserID adds the userID to the get campaigns stats params
func (o *GetCampaignsStatsParams) WithUserID(userID int64) *GetCampaignsStatsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get campaigns stats params
func (o *GetCampaignsStatsParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCampaignsStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-RequestID
	if err := r.SetHeaderParam("X-RequestID", o.XRequestID); err != nil {
		return err
	}

	// path param account_id
	if err := r.SetPathParam("account_id", swag.FormatInt64(o.AccountID)); err != nil {
		return err
	}

	if o.CampaignIds != nil {

		// binding items for campaign_ids
		joinedCampaignIds := o.bindParamCampaignIds(reg)

		// query array param campaign_ids
		if err := r.SetQueryParam("campaign_ids", joinedCampaignIds...); err != nil {
			return err
		}
	}

	if o.ClientID != nil {

		// query param client_id
		var qrClientID int64

		if o.ClientID != nil {
			qrClientID = *o.ClientID
		}
		qClientID := swag.FormatInt64(qrClientID)
		if qClientID != "" {

			if err := r.SetQueryParam("client_id", qClientID); err != nil {
				return err
			}
		}
	}

	if o.DateFrom != nil {

		// query param date_from
		var qrDateFrom int64

		if o.DateFrom != nil {
			qrDateFrom = *o.DateFrom
		}
		qDateFrom := swag.FormatInt64(qrDateFrom)
		if qDateFrom != "" {

			if err := r.SetQueryParam("date_from", qDateFrom); err != nil {
				return err
			}
		}
	}

	if o.DateTo != nil {

		// query param date_to
		var qrDateTo int64

		if o.DateTo != nil {
			qrDateTo = *o.DateTo
		}
		qDateTo := swag.FormatInt64(qrDateTo)
		if qDateTo != "" {

			if err := r.SetQueryParam("date_to", qDateTo); err != nil {
				return err
			}
		}
	}

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}

	if o.UpdatedSince != nil {

		// query param updated_since
		var qrUpdatedSince int64

		if o.UpdatedSince != nil {
			qrUpdatedSince = *o.UpdatedSince
		}
		qUpdatedSince := swag.FormatInt64(qrUpdatedSince)
		if qUpdatedSince != "" {

			if err := r.SetQueryParam("updated_since", qUpdatedSince); err != nil {
				return err
			}
		}
	}

	// query param user_id
	qrUserID := o.UserID
	qUserID := swag.FormatInt64(qrUserID)
	if qUserID != "" {

		if err := r.SetQueryParam("user_id", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetCampaignsStats binds the parameter campaign_ids
func (o *GetCampaignsStatsParams) bindParamCampaignIds(formats strfmt.Registry) []string {
	campaignIdsIR := o.CampaignIds

	var campaignIdsIC []string
	for _, campaignIdsIIR := range campaignIdsIR { // explode []int64

		campaignIdsIIV := swag.FormatInt64(campaignIdsIIR) // int64 as string
		campaignIdsIC = append(campaignIdsIC, campaignIdsIIV)
	}

	// items.CollectionFormat: ""
	campaignIdsIS := swag.JoinByFormat(campaignIdsIC, "")

	return campaignIdsIS
}

// bindParamGetCampaignsStats binds the parameter fields
func (o *GetCampaignsStatsParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: ""
	fieldsIS := swag.JoinByFormat(fieldsIC, "")

	return fieldsIS
}
